/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleexample;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {
    @Test void isPositiveNumberTest() {
        assertTrue(StringUtils.isPositiveNumber("123"), "\"123\" should be true");
        assertFalse(StringUtils.isPositiveNumber("abc"), "\"abc\" should be false");
        assertFalse(StringUtils.isPositiveNumber("-123"), "\"-123\" should be false");
    }
}
