/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi.project.core;

import static gradleexample.StringUtils.*;

public class Utils {
    public static boolean isAllPositiveNumbers(String... str) {
	    for(String string: str) {
		    if(!isPositiveNumber(string)){
			    return false;
		    }
	    }
	    return true;
    }
}
