/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleexample;

import java.util.Objects;

public class StringUtils {
    public static boolean isPositiveNumber(String str) {

        if (Objects.isNull(str)) {
            return false;
        }

        if(! org.apache.commons.lang3.StringUtils.isNumeric(str)) {
            return false;
        }

        Double doubleValue = null;

        try {
            doubleValue = Double.valueOf(str);
        } catch (NumberFormatException e) {
            return false;
        }

        return doubleValue > 0.0;

    }
}
